version: '2'
services:
  redis:
   image: redis:3.2.11-alpine
   hostname: redis
   expose:
     - "6379"
  app:
    build: ./apps
    working_dir: /apps
    hostname: app
    volumes:
      - ./apps:/apps
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - redis
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
     - "80:80"
     - "443:443"
   volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d
   links:
     - app
